### ISSUE TITLE
when we making client

### ISSUE THREAD

**Issue by Cabbasca** [SomeBoringNerd/WaifuHax#2]
when are we making a client together man?

**Comment by SomeBoringNerd** [comment]
Probably not now, first of all I suck at making clients, secondly I'm a student in exam year.

Thank for considering tho

**Comment by Cabbasca** [comment]
I wouldn't say you suck at making clients, your client making ability might need some work though
btw if you ever change your mind anytime soon make sure to contact me at Trolman#9026 on discord(assuming you have discord?)
